/**
 * 图标提取工具（可复现）
 * ------------------------------------------------------------
 * 从项目 node_modules/lucide-react 的 ESM 图标模块中抽取 __iconNode
 * 路径数据，生成 js/core/icons.generated.js。设计稿不依赖任何网络或
 * 运行时框架，图标全部内联；桌面端 lucide-react 升级后重跑本脚本即可同步：
 *
 *   node 设计稿/Windows/tools/extract-icons.mjs
 *
 * 图标许可：lucide-react ISC（与主项目依赖一致）。
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const ICONS_DIR = join(here, "..", "..", "..", "node_modules", "lucide-react", "dist", "esm", "icons");
const OUT = join(here, "..", "js", "core", "icons.generated.js");

/** 设计稿实际使用到的图标清单（kebab-case，与 lucide 文件名一致）。 */
const ICON_NAMES = [
  // 基础操作 / 窗口控制
  "check", "plus", "x", "minus", "square", "search", "search-x", "menu",
  "more-horizontal", "copy", "command", "pin", "external-link",
  "signal", "wifi", "battery",
  "pencil", "trash-2", "rotate-ccw", "skip-forward", "arrow-left",
  "arrow-up", "arrow-down", "arrow-down-up",
  "chevron-left", "chevron-right", "chevron-down", "chevron-up", "chevrons-up",
  // 任务与视图
  "list", "list-todo", "list-checks", "inbox", "star", "flag", "clock",
  "timer", "target", "alarm-clock",
  "calendar", "calendar-days", "calendar-clock", "calendar-range", "calendar-x-2",
  "calendar-check", "check-circle", "check-circle-2", "check-check", "check-square",
  "alert-circle", "kanban",
  // 循环 / 提醒 / 标签 / 附件 / 关联
  "repeat", "repeat-2", "bell", "bell-off", "bell-ring", "tag", "paperclip",
  "link-2", "sliders-horizontal", "filter", "grip-vertical", "folder-input",
  // 主题 / 同步 / 工具
  "sun", "moon", "cloud", "cloud-off", "cloud-alert", "refresh-cw",
  "flame", "trending-up", "sparkles", "palette", "settings", "droplet", "type",
  "database", "download", "upload", "info", "shield", "smartphone",
  "monitor-smartphone", "hard-drive", "archive", "history", "volume-2",
  "volume-x", "layout-grid", "folder", "folder-plus", "folder-open", "hash",
  "home", "power", "keyboard", "bar-chart-3", "git-compare", "file-text",
  "panel-left-close",
  // 播放控制（专注）
  "play", "pause",
  // 日历事件类型
  "plane", "palmtree", "circle", "circle-dot",
  // 桌面便签
  "sticky-note",
  // 清单 / 浏览
  "layers",
];

function extractNode(file, seen = new Set()) {
  if (seen.has(file)) throw new Error(`cyclic re-export at ${file}`);
  seen.add(file);
  const src = readFileSync(file, "utf8");
  // 兼容别名文件：export { default } from './ellipsis.mjs';
  const reExport = src.match(/export \{ default \} from '\.\/(.+?)\.mjs';/);
  if (reExport) {
    return extractNode(join(ICONS_DIR, `${reExport[1]}.mjs`), seen);
  }
  const match = src.match(/const __iconNode = (\[[\s\S]*?\]);\s*\n/);
  if (!match) throw new Error(`__iconNode not found in ${file}`);
  // 源文件里的数组字面量是合法 JS，直接用 Function 求值（内容来自固定依赖，非用户输入）
  return Function(`"use strict";return (${match[1]});`)();
}

const missing = [];
const out = {};
for (const name of ICON_NAMES) {
  const file = join(ICONS_DIR, `${name}.mjs`);
  if (!existsSync(file)) {
    missing.push(name);
    continue;
  }
  out[name] = extractNode(file);
}

if (missing.length) {
  console.warn("[extract-icons] 以下图标在当前 lucide-react 版本中不存在，已跳过：");
  for (const name of missing) console.warn("  -", name);
}

const banner = `/* AUTO-GENERATED by tools/extract-icons.mjs — 请勿手改。
   数据源：node_modules/lucide-react (ISC)。重跑：node tools/extract-icons.mjs */`;

const body = `${banner}
export const ICON_PATHS = ${JSON.stringify(out, null, 2)};
`;
writeFileSync(OUT, body, "utf8");
console.log(`[extract-icons] 已生成 ${OUT}，共 ${Object.keys(out).length} 个图标。`);
